image: node:8.12.0

stages: 
  - build
  - test
  # - production

cache:
  paths:
    - node_modules/

install-dependencies:
  stage: build
  script: 
    - npm install
  artifacts:
    paths:
      - node_modules/

lint-checks:
  stage: test
  script: 
    - npm run lint
    - npm run test

# write the heroku-deployment job here 
# production:
#   type: deploy
#   stage: production
#   image: ruby:latest
#   script:
#     - apt-get update -qy
#     - apt-get install -y ruby-dev
#     - gem install dpl
#     - dpl --provider=heroku --app=socket-io-stackroute --api-key=$HEROKU_API_KEY
#   only:
#     - master